In [2]:
import numpy as np
import pandas as pd
import mne ,os

In [55]:
db_patients_path  = '/home/tusharsingh/DATAs/Database_patients'
db_subjects_path  = '/home/tusharsingh/DATAs/Database_subjects'

scoring_criteria = 'HypnogramR&K_'
def file_path_aggregator(scoring_criteria, path, count, prefix):
    edf = [os.path.join(path,prefix + str(i) + '.edf') for i in range(1, count + 1)]
    txt = [os.path.join(path,scoring_criteria + prefix + str(i) + '.txt') for i in range(1, count + 1)]
    return list(zip(edf, txt))

def data_aggregator(path_list):
    EDF = []
    label = []
    error = 0
    for edf, txt in path_list:
        name = txt[-13:]
        e = mne.io.read_raw_edf(edf, verbose = False)
        # because channel name is not consistent in differnt files, 
        # hence need to search for EOG1 prefix
        x = sorted([a for a in e.ch_names if 'EOG1' in a])[0]
        # print(x)
        edf = e.pick(x).to_data_frame()[x].values
        with open(txt,'r') as f:
            lines = f.readlines()[1:]
            lines = [int(x[:-1]) for x in lines]
            txt = np.array(lines)
            # sleep
            # txt[txt != 5] = 1
            # wake
            # txt[txt == 5] = 0

        txt = txt[:4*(txt.size//4)]
        edf = edf[:txt.size * 1000]
        txt = txt.reshape(-1,4)
        edf = edf.reshape(-1,4000)

        if not (txt[:,0] == np.mean(txt, axis = 1)).all():
            print(name, "     edf_shape", edf.shape, " txt_shape", txt.shape)
            print(txt[txt[:,0] != np.mean(txt, axis = 1)])

    print(error)
    return list(zip(EDF, label))

In [57]:
patient_paths = file_path_aggregator(scoring_criteria, db_patients_path, 27, 'patient')
subject_paths = file_path_aggregator(scoring_criteria, db_subjects_path, 20, 'subject')

patient_data = data_aggregator(patient_paths)
subject_data = data_aggregator(subject_paths)

patient11.txt      edf_shape (1619, 4000)  txt_shape (1619, 4)
[[2 2 5 5]]
patient18.txt      edf_shape (1876, 4000)  txt_shape (1876, 4)
[[2 2 5 5]
 [2 2 5 5]]
patient23.txt      edf_shape (1462, 4000)  txt_shape (1462, 4)
[[4 4 2 2]
 [2 2 5 5]]
patient24.txt      edf_shape (1390, 4000)  txt_shape (1390, 4)
[[5 5 3 3]
 [5 5 3 3]
 [5 5 3 3]
 [3 3 2 2]
 [2 2 3 3]
 [2 2 4 4]
 [4 4 5 5]
 [3 3 2 2]
 [2 2 5 5]
 [3 3 2 2]
 [5 5 3 3]
 [3 3 2 2]
 [2 2 3 3]
 [2 2 3 3]
 [3 3 2 2]
 [2 2 3 3]
 [2 2 3 3]
 [3 3 2 2]
 [3 3 2 2]
 [2 2 5 5]
 [5 5 3 3]
 [3 3 2 2]
 [3 3 2 2]
 [2 2 4 4]
 [3 3 2 2]
 [4 4 3 3]
 [5 5 3 3]
 [5 5 3 3]
 [2 2 3 3]
 [3 3 2 2]
 [2 2 3 3]
 [2 2 3 3]
 [2 2 3 3]
 [3 3 5 5]
 [3 3 2 2]
 [2 2 4 4]
 [5 5 3 3]
 [3 3 5 5]
 [5 5 3 3]
 [3 3 2 2]
 [2 2 3 3]
 [3 3 2 2]
 [3 3 2 2]
 [2 2 3 3]
 [3 3 2 2]
 [2 2 3 3]
 [2 2 3 3]]
patient25.txt      edf_shape (1619, 4000)  txt_shape (1619, 4)
[[5 5 3 3]
 [2 2 5 5]
 [5 5 3 3]
 [2 2 5 5]
 [2 2 3 3]
 [2 2 3 3]
 [2 2 4 4]
 [4 4 2 2]
 [2 2 3 3]
 [2 2 1 1]

In [23]:
for eog, label in subject_data:
    print(eog.shape, label.shape)

(1442, 4000) (1442,)
(1477, 4000) (1477,)
(1513, 4000) (1513,)
(1579, 4000) (1579,)
(1564, 4000) (1564,)
(1496, 4000) (1496,)
(1518, 4000) (1518,)
(1455, 4000) (1455,)
(1676, 4000) (1676,)
(1549, 4000) (1549,)
(1512, 4000) (1512,)
(1442, 4000) (1442,)
(1667, 4000) (1667,)
(1506, 4000) (1506,)
(1260, 4000) (1260,)
(1451, 4000) (1451,)
(1495, 4000) (1495,)
(1532, 4000) (1532,)
(1550, 4000) (1550,)
(1717, 4000) (1717,)


In [22]:
for eog, label in patient_data:
    print(eog.shape, label.shape)

(1445, 4000) (1445,)
(1536, 4000) (1536,)
(1643, 4000) (1643,)
(1563, 4000) (1563,)
(1508, 4000) (1508,)
(1504, 4000) (1504,)
(1480, 4000) (1480,)
(1711, 4000) (1711,)
(1520, 4000) (1520,)
(1621, 4000) (1621,)
(1619, 4000) (1619,)
(1556, 4000) (1556,)
(1464, 4000) (1464,)
(1596, 4000) (1596,)
(1425, 4000) (1425,)
(1718, 4000) (1718,)
(1681, 4000) (1681,)
(1876, 4000) (1876,)
(1615, 4000) (1615,)
(1481, 4000) (1481,)
(1681, 4000) (1681,)
(1658, 4000) (1658,)
(1462, 4000) (1462,)
(1390, 4000) (1390,)
(1619, 4000) (1619,)
(1501, 4000) (1501,)
(1602, 4000) (1602,)
